Exercise 1.


Consider 

$$
Max_{c_t, k_{t+1}}= \Biggr[\sum_{t=0}^{\infty} \beta^t \ ln \ c_t \Biggr]\\
$$

$$
k_{t+1}=k^\alpha_t - c_t \ ; \ t=0,1,2,...
$$

(a) Set up the infinite horizon Lagrangean and take the first order condition

(b) Obtain a non linear system of 2 equations in kt; ct (over and above the transversality condition).

(c) Briefly describe and derive the steady state of the system.

(d) Log linearize the two by two system.

__The answer to the questions above are full explained step-by-step in the PDF__

(e) Put the system in state space.

(f) Discuss why or why not the system can satisfy the Blanchard Khan conditions.

(g) Assume   $\alpha$= 0.33,   $\beta$= 0.98 and write a Python Code for solving the system of
di erence equation. Obtain the eigenvalues.....

(h) What is the policy function of the linear system and what is the transition function? Obtain the numeric expressions of the two functions.

(e) Put the system in state space.

$$
\begin{bmatrix}
    -(\alpha-1) &  1   \\
    1 & 0 \\
\end{bmatrix}
\begin{bmatrix}
    k_{t+1}\\
    c_{t+1}\\
\end{bmatrix}
=
\begin{bmatrix}
    0 & 1  \\
    \frac{1}{\beta} & -\frac{c}{k} \\
\end{bmatrix}
\begin{bmatrix}
    k_t\\
    c_t \\
\end{bmatrix}
$$


Putting values 


$$
\begin{bmatrix}
    -(\alpha-1) &  1   \\
    1 & 0 \\
\end{bmatrix}
\begin{bmatrix}
    k_{t+1}\\
    c_{t+1}\\
\end{bmatrix}
=
\begin{bmatrix}
    0 & 1  \\
    \frac{1}{\beta} & -\frac{c}{k} \\
\end{bmatrix}
\begin{bmatrix}
    k_t\\
    c_t \\
\end{bmatrix}
$$

(f) Discuss why or why not the system can satisfy the Blanchard Khan conditions.

Yes, the systen can sastify the BK conditions since it first condition (as will be shown after), the invertibilyy of T0; is fullfilled. 


In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


alpha=0.33
beta=0.98

L0=np.asmatrix(np.zeros((2,2)))
L1=np.asmatrix(np.zeros((2,2)))

L0[0,0]=-alpha+1
L0[0,1]=1
L0[1,0]=1

L1[0,1]=1
L1[1,0]=1/beta
L1[1,1]=-(1/(alpha*beta)-1)

if np.linalg.det(L0)!=0:
    print('the matrix L0 is invertible')
    A=np.linalg.inv(L0)*L1
    print(A)
else:
    print('the matrix L0 is not invertible')


the matrix L0 is invertible
[[ 1.02040816 -2.09214595]
 [-0.68367347  2.40173779]]


In [3]:
####################################
# CALCULATE EIGNEVALUES
####################################
#DEFINE AS AS IN THE NOTES
A=np.linalg.inv(L0)*L1

#%%
w,ve=np.linalg.eig(A)

#w are the eigenvalues
#ve is the matrix of eigenvector
#%%
#Create matrix of eigenvalues
MU=np.asmatrix(np.zeros((2,2)))
MU[0,0]=w[0]
MU[1,1]=w[1]

#SHOULD BE AS A
AP=ve*MU*np.linalg.inv(ve)

#Check Diagonlization
DD=AP-A
DD=abs(DD)
if DD.max()<10**(-5):
    print("Matrix A has been diagonalized")
else:
    print("Diagonalization failed")
    
#trace of A
traceA=A[0,0]+A[1,1]

#Determinant of A
detA=A[0,0]*A[1,1]-A[0,1]*A[1,0]

#%%
#Check linear Algebra Properties
if detA-w[0]*w[1]<10**(-5):
    print ("determinant A is product of eigenvalue")
else:
    print ("Linear Algebra properties not satisfied")        
     
if traceA-(w[0]+ w[1])<10**(-5):
    print ("Trace of  A is sum of eigenvalue")
else:
    print ("Linear Algebra properties not satisfied")        


Matrix A has been diagonalized
determinant A is product of eigenvalue
Trace of  A is sum of eigenvalue


In [4]:
eigenValues,eigenVectors = np.linalg.eig(A)
#eigenValues is w 
#eigenVectors is v

idx = eigenValues.argsort()[::-1]  # return the index of  largest to smallest 
eigenValues = eigenValues[idx]  #sort from largest to smallets
eigenVectors = eigenVectors[:,idx]  #sort eigenvectors

if eigenValues[1] >= 1: #smallest larger than one
    print ("no saddle path, both eigenvalues larger than one")
elif eigenValues[0] <= 1: #largest smaller than
    print ("no saddle path, both eigenvalues smaller than one")
else:
    print  ("Saddle Path passed")
    print ("One eigenvalue is greater that one and one is lower than one") 
    print (eigenValues)

Saddle Path passed
One eigenvalue is greater that one and one is lower than one
[3.09214595 0.33      ]


In [5]:
#%%
##################################
#ASSIGN EIGENVALUES
#################################

#s are for state variables
#assign it to capital
lam_s1=eigenValues[1]  #eigenvalues in the highest index is the smallest


#u are for controls
#lam_u=MU[1,1]  #unstable eigenvalue for consumption
lam_u=eigenValues[0]  #eigenvalues in the lowest index is the largest

#Create Matrix Variable to double check
MUT=np.eye(2)
MUT[0,0]=lam_s1
MUT[1,1]=lam_u

veT=np.asmatrix(np.zeros((2,2)))
#ORDER EIGENVECTORS COHERENT WITH EIGENVALUES
veT[:,0]=eigenVectors[:,1]
veT[:,1]=eigenVectors[:,0]
WT=veT*MUT*np.linalg.inv(veT)  #shoule be identical to AP

MUT

array([[0.33      , 0.        ],
       [0.        , 3.09214595]])

In [7]:

P=veT
Pinv=np.linalg.inv(veT) 

P_11=np.asmatrix(np.zeros((1,1)))
P_12=np.asmatrix(np.zeros((1,1)))
P_21=np.asmatrix(np.zeros((1,1)))
P_22=np.asmatrix(np.zeros((1,1)))



P_11[0,0]=P[0,0]
P_12[0,0]=P[0,1]
P_21[0,0]=P[1,0]
P_22[0,0]=P[1,1]


Pinv_11=np.linalg.inv(P_11)


In [8]:
detP=P_11[0,0]*P_22[0,0]-P_12[0,0]*P_21[0,0]    

    
def sequence(dk0,dc0,t):
    
    dct=np.zeros(t) #zero array for consumption
    dkt=np.zeros(t) #zero array for capital
    for i in range(t):
       

        dct[i]=P_21*(lam_s1**(i+1))*(P_22*dk0-P_12*dc0)+P_22*(lam_u**(i+1))*(-P_21*dk0+P_11*dc0)
        dct[i]=dct[i]/detP
        
        
        dkt[i]=P_11*(lam_s1**(i+1))*(P_22*dk0-P_12*dc0)+P_12*(lam_u**(i+1))*(-P_21*dk0+P_11*dc0)
        dkt[i]=dkt[i]/detP
        
    
    return dct , dkt  #a list

In [9]:
#POLICY AND TRANSITION FUNCTION
POL=P_21*Pinv_11

A11=A[0,0]
A12=A[0,1]

TRANS=A11+A12*POL

print("policy function:", POL)
print("transition function:", TRANS)


policy function: [[0.33]]
transition function: [[0.33]]


__Now we try to solve the same model using the _linearsolve__

In [26]:
# Import numpy, pandas, linearsolve, matplotlib.pyplot
import numpy as np
import pandas as pd
import linearsolve as ls
import matplotlib.pyplot as plt
plt.style.use('classic')

# Input model parameters
parameters = pd.Series(dtype=float)
parameters['alpha']  = 0.33
parameters['beta']  = 0.98

# Funtion that evaluates the equilibrium conditions
def equations(variables_forward,variables_current,parameters):

    # Parameters
    p = parameters

    # Variables
    fwd = variables_forward
    cur = variables_current

    # Household Euler equation
    euler_eqn = p.alpha*fwd.k**(p.alpha - 1)- fwd.c / (p.beta * cur.c)

    # Goods market clearing
    constraints= fwd.k + cur.c - (cur.k**p.alpha)

    # Stack equilibrium conditions into a numpy array
    return np.array([
            euler_eqn,
            constraints
        ])

# Initialize the model
model = ls.model(equations = equations,
                 n_states=1,
                 n_exo_states = 1,
                 var_names=['k','c'],
                 parameters = parameters)

guess = [0.2,0.4]
model.compute_ss(guess)

model.approximate_and_solve()
     

print("Transition function:",model.f)
print("Policy function:", model.p)
print(model.eig)



Transition function: [[0.33]]
Policy function: [[0.33]]
[0.33      +0.j 3.09214595+0.j]


Exercise 2. 


$$
Max_{[c_t,n_t,k_{t+1}]_{t=0}^\infty}\sum_{t=0}^{\infty} \beta^t [lnc_t + \phi ln(1-n_t)
$$

$$
c_t+k_{t+1}-1(1-\delta)k_t=z_tk_t^{\alpha}n_t^{1-\alpha} \ \ \ k_0 \ is \ given
$$

(a) Set up the Lagrangean and show that the  rst order conditions are

$$
\frac{1}{c_t}=\frac{\beta}{c_{t+1}}[z_{t+1}\alpha k_{t+1}^{\alpha-1}n_{t+1}^{1-\alpha}+1-\delta]\\
$$

$$
\frac{\phi c_t}{1-n_t}=(1-\alpha)z_tk_t^\alpha n_t^{-\alpha}
$$

$$
TVC
$$

where TVC is the trasversality condition.

(b) Log linearize the  rst order conditions.

(c) Write the model in State space form $\Gamma_0 X_{t+1} = \Gamma_1 X_{t}$  and show that  $\Gamma_0$ is not invertible.

(d) Use the Schur decomposition and explain brieflyy how to obtain the generalized eigenvalues for the problem at hand

(e) Write a simple code with values   $\phi$= 0.5,  $\beta$ = 0.98 and $\alpha$=0.3 and shows
numerically that the model has a unique stable steady state. For the value of zt
simply assumes that is equal to 1 $\forall t $

(f) Obtain numerically the policy function and the transition function.

In [51]:
import numpy as np
import scipy.linalg as la
import scipy

################################
#SPARAMETERS  

alpha = 0.3
beta = 0.98
phi = 0.5
delta = 0.08
z=1
#others exog. parameter
    
n= 1/3 #as in the lectures about how much people work

################################
#STEADY STATE VALUES
##################################
     
k= ((alpha*(n)*(1-alpha))/((1/beta)-1+delta))*(1/(1-alpha))
c = k**(alpha)*n**(1-alpha)-delta*k 

#ORDER OF VARIABLES IS
#k_t
#n_t
#c_t

L0=np.asmatrix(np.zeros((3,3)))
L1=np.asmatrix(np.zeros((3,3)))

L0[0,0] = -beta*(alpha-1)*((1/beta)-1+delta)
L0[0,1] = -beta*(1-alpha)*((1/beta)-1+delta)
L0[0,2] = 1

L0[2,0] = (k/(c+delta*k))



L1[0,2] = 1

L1[1,0] = alpha
L1[1,1] = -((n/(1-n))-alpha) 
L1[1,2] = -1

L1[2,0] = alpha+(((1-delta)*k)/(c+delta*k)) 
L1[2,1] = 1 - alpha
L1[2,2] = -(c/(c+delta*k))


np.linalg.det(L0)

0.0

In [52]:
nvar=3
nk=1

AA,BB,a,b,q,z=la.ordqz(L0, L1, sort='ouc', output='complex')

lambda1=  (BB[0,0]/AA[0,0])
lambda2=  (BB[1,1]/AA[1,1])
lambda3=  (BB[2,2]/AA[2,2])

print(lambda1,lambda2,lambda3)

geEigenvalues=np.zeros(nvar)

for ii in range(nvar):
    geEigenvalues[ii]=np.real(BB[ii,ii]/AA[ii,ii]) 
if abs(geEigenvalues[nk-1])<1:
    print ("Generalized decomposition satisfies stability property")
if abs(geEigenvalues[nk-1])>1:
    print ("Problems with Generalized decomposition ")


(0.7988088712639005+0j) (-2611686236875531.5-0j) (1.4409486997186531+0j)
Generalized decomposition satisfies stability property


In [53]:
z21 = z[nk:nvar,0:nk]  

z11 = z[0:nk,0:nk]  
z21=np.asmatrix(z21)
z11=np.asmatrix(z11)

z11=np.asmatrix(z11)
z11i = np.linalg.inv(z11)
s11 = AA[0:nk,0:nk]
t11 = BB[0:nk,0:nk]
z11i=np.asmatrix(z11i)
s11=np.asmatrix(s11)
t11=np.asmatrix(t11)

z12=z[0:nk,nk:nvar]
z12=np.asmatrix(z12)
z22=z[nk:nvar,nk:nvar]
z22=np.asmatrix(z22)

dyn=np.linalg.inv(s11)*t11

G_k = np.real(z21*z11i)
p = np.real(z11*dyn*z11i)
G=np.real(-np.linalg.inv(z22.transpose())*z12.transpose())


print("Policy Function for n and c at time t (give me state today and I will give you control today")
print (G)
print("Transition Function for k at time t+1 (state and contro today and I will give you state tomorrow )")
print (p)

Policy Function for n and c at time t (give me state today and I will give you control today
[[-0.36089565]
 [ 0.37217913]]
Transition Function for k at time t+1 (state and contro today and I will give you state tomorrow )
[[0.79880887]]


__Using linear solve__

Disclaimer: I was not able to obtain the same results as before. I try to using the log linear version of the model but resutls were not succesful. 

In [54]:
import numpy as np
import pandas as pd
import linearsolve as ls
import matplotlib.pyplot as plt
plt.style.use('classic')
%matplotlib inline

In [61]:
import numpy as np
import pandas as pd
import linearsolve as ls
import matplotlib.pyplot as plt
plt.style.use('classic')

beta=0.98
phi=0.5
delta=0.3
alpha=0.33
z=1
Nbar=1/3

Kbar= ((alpha*(n)*(1-alpha))/((1/beta)-1+delta))*(1/(1-alpha))
Cbar= Kbar**(alpha)*n**(1-alpha)-delta*Kbar

parameters = pd.Series(dtype=float)
parameters['alpha'] = alpha
parameters['beta'] = beta
parameters['delta']= delta
parameters['phi']= phi
parameters['z']= z

def equations(variables_forward,variables_current,parameters):

    # Parameters
    p = parameters

    # Variables
    fwd = variables_forward
    cur = variables_current

    euler_eqn = (p.beta/fwd.c)*p.alpha*p.z*fwd.k**(p.alpha-1)*fwd.n**(1-p.alpha)+(1-p.delta) - 1/cur.c

    markert_clearing = - cur.c - fwd.k + p.z*cur.k**(p.alpha)*cur.n**(1-p.alpha) + (1-p.delta)*cur.k
    
    labor_eqn = - cur.c*p.phi/(1-cur.n) + (1-p.alpha)*p.z*cur.k**p.alpha*cur.n**(-p.alpha)
           
    # Stack equilibrium conditions into a numpy array
    return np.array([
            euler_eqn,
            markert_clearing,
            labor_eqn
        ])

model = ls.model(equations = equations,
                 n_states=1,
                 n_exo_states = 0,
                 var_names=['k','c','n'],
                 parameters = parameters)

guess = [0.9,0.38,1/3]
model.compute_ss(guess)

model.approximate_and_solve(log_linear=1)
model.solve_klein()
print("policy function" ,model.f)
print("transition function" , model.p)


policy function [[ 0.43313488]
 [-0.05523935]]
transition function [[0.50199434]]


/var/folders/9_/_lsvdc991cncn4pl9dlgsq_80000gn/T/ipykernel_39806/1532394906.py:33: RuntimeWarning: invalid value encountered in double_scalars
  euler_eqn = (p.beta/fwd.c)*p.alpha*p.z*fwd.k**(p.alpha-1)*fwd.n**(1-p.alpha)+(1-p.delta) - 1/cur.c
/var/folders/9_/_lsvdc991cncn4pl9dlgsq_80000gn/T/ipykernel_39806/1532394906.py:35: RuntimeWarning: invalid value encountered in double_scalars
  markert_clearing = - cur.c - fwd.k + p.z*cur.k**(p.alpha)*cur.n**(1-p.alpha) + (1-p.delta)*cur.k
/var/folders/9_/_lsvdc991cncn4pl9dlgsq_80000gn/T/ipykernel_39806/1532394906.py:37: RuntimeWarning: invalid value encountered in double_scalars
  labor_eqn = - cur.c*p.phi/(1-cur.n) + (1-p.alpha)*p.z*cur.k**p.alpha*cur.n**(-p.alpha)
/var/folders/9_/_lsvdc991cncn4pl9dlgsq_80000gn/T/ipykernel_39806/1532394906.py:33: RuntimeWarning: invalid value encountered in double_scalars
  euler_eqn = (p.beta/fwd.c)*p.alpha*p.z*fwd.k**(p.alpha-1)*fwd.n**(1-p.alpha)+(1-p.delta) - 1/cur.c
/var/folders/9_/_lsvdc991cncn4pl9dlgsq